packages:
  - packages/api
  - packages/upload-button
  - packages/dropzone
  - packages/uploader
  - packages/preact-vue-connect
  - packages/preact-react-connect
  - examples/nuxt
  - examples/sevlet
  - examples/react

